import os
os.system ("clear")
def menu():

    print ("\033[0;32m                               .~%%%%%%%%%%%;~.")
    print ("\033[0;32m                             /%%%%%%%%%%%%%%;:\ ")
    print ("\033[0;32m                            /%%%%%%/~\/~\;;;,;,\,")
    print ("\033[0;32m                           |%%%%%%^\    /;;;;.,.|")
    print ("\033[0;32m                           |%%%%%%%%%\/;;;;;;.,.|")
    print ("\033[0;33m                  XX       |%%/~~\%%%%%;;;/~~\;,|       XX")
    print ("\033[0;33m                XX..X      |%|  o  \%%%;/  o  |.|      X..XX")
    print ("\033[0;33m              XX.....X     |%%\____/%%%;\____/.,|     X.....XX")
    print ("\033[0;33m          XXXXX.....XX      \%%%%%%%%%/\;;;;;;,, /      XX.....XXXXX")
    print ("\033[0;33m        X |......XX%,.@      \%%%%%%/%;\;;;;, /      @@%,XX......| X")
    print ("\033[0;33m        X |.....X  @@%,.@     |%%%%%%%%;;;;,.|     @@%,.@  X.....| X")
    print ("\033[0;33m        X  \...X     @@%,.@   |% % % % ; ; ;,|   @@%,.@     X.../  X")
    print ("\033[0;33m         X@ \.X        @@%,.@                  @@%,.@        X./  @")
    print ("\033[0;31m          @  X          @@%,.@              @@%,.@          X   @")
    print ("\033[0;31m        , :@ @X            @@%,.@          @@%,.@            X @@")
    print ("\033[0;31m           :@@@X             @@%,.@      @@%,.@             @@@@:")
    print ("\033[0;31m          . :@@@#              @@%.,@  @@%,.@              @@@@:")
    print ("\033[0;31m            . :;:                @@%.@@%,.@                ;:: : .")
    print ("\033[0;31m              :                    @@%,.@                   ,.")
    print ("\033[0;31m              : ,                @@%,.@  @@                :")
    print ("\033[0;31m                                  @@@  @@@ ")
    print ("                                                                                ")
    print ("\033[0;32m                             FREE   < _ >   HACK                      ")
    print ("                                                                              ")
    print ("\033[0;33m                  yuotupe ==>   https://youtu.be/hqeIvjJo5Pg         ")
    print ("                                                                      ")

loop = True

while loop:
    menu()
    print ("                                                                               ")
    print ("                                                                                ")
    print ("\033[0;34m  install termux [1] ")
    print ("                                                                               ")
    print ("                                                                                                                                >
    what = input("\033[0;34m  FREE=>HACK==>  ")
    if what == "1":
        print ("\033[0;32m   _____   _____    _____   _____        _   _")
        print ("\033[0;32m  |  ___| |  _  \  | ____| | ____|      | | | |     /   | /  ___| | | / /")
        print ("\033[0;32m  | |__   | |_| |  | |__   | |__        | |_| |    / /| | | |     | |/ /")
        print ("\033[0;32m  |  __|  |  _  /  |  __|  |  __|       |  _  |   / / | | | |     | |\ \ ")
        print ("\033[0;32m  | |     | | \ \  | |___  | |___       | | | |  / /  | | | |___  | | \ \  ")
        print ("\033[0;32m  |_|     |_|  \_\ |_____| |_____|      |_| |_| /_/   |_| \_____| |_|  \_\ ")
        print ("                                                                                     ")
        Ali = input("Do you want to install orders 'termux' (y/n): ")
        if Ali == "y":
            print("[+] Please orders are being installed 'wait' ")
            os.system("apt-get install screenfetch -y")
            os.system("screenfetch")
            os.system("apt-get update -y")
            os.system("apt-get upgrade")
            os.system("apt-get install python -y")
            os.system("apt-get install python2 -y")
            os.system("apt-get install python3 -y")
            os.system("apt-get install ruby -y")
            os.system("apt-get install git -y     ")                                                                              os.system("apt-get install php -y")
            os.system("apt-get install nano -y")
            os.system("apt-get install nmap -y")
            os.system("apt-get install perl -y")
            os.system("termux-setup-storage -y")
            os.system("apt-get install golang -y")
            pos.system("apt-get install host -y")
            os.system("apt-get install havij -y")
            os.system("apt-get install hydra -y")
            os.system("apt install wireshark -y")
            os.system("apt-get install cmatrix -y")
            os.system("apr-get install figlet -y")
            os.system("apt-get install wget -y")
            os.system("apt-get install python2 -y")
            os.system("apt-geg install python2-dev -y")                                                                           os.system("apt install wireshark -y")
            os.system("apt-get install cmatrix -y")
            os.system("apr-get install figlet -y")                                                                                os.system("apt-get install wget -y")
            os.system("apt-get install wget -y")
            os.system("apt-get install python2 -y")
            os.system("apt-geg install python2-dev -y")                                                                           os.system("apt install wireshark -y")
            os.system("apt-get install cowsay -y")
            os.system("apt-get install toilet -y") 
            os.system("apt-get install curlinstall wgetrc -y")
            os.system("apt-get install ruby -y")
            os.system("apt-get install help -y")
            os.system("apt-get install net-tools -y")
            os.system("apt-get install w3m -y")
            os.system("apt-get install unrar -y ")
            os.system("apt-get install clang -y")
            os.system("apt-get install openssh -y")
            os.system("apt-get install tor -y")
            os.system("apt-get install tar -y")
            os.system("apt-get install zip -y")
            os.system("apt-get install proot -y")
            os.system("pip2 install wget -y")
            os.system("pip2 install requests -y")
            os.system("gem install lolcat -y")
            os.system("apt update -y && apt upgrade -y")
            os.system("clear")

            fgf = input ("\033[0;30m [+]  To reinstall me press( y/n) ")
            if fgf == "y":

                menu()                                                                                                            else:
                break
    elif what == "00":
        print("FREE HACK xx ")
        break
